site: wdc
environment: prod
ingress:
  enabled: true
  host: www.wakeboard.com
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: sha-3aeb14e
imagePullSecrets:
  - name: ghcr-login-secret
