site: wsf
environment: prod
ingress:
  enabled: true
  host: www.wakesurfuk.com
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: sha-41b4db3
imagePullSecrets:
  - name: ghcr-login-secret

