site: wsf
environment: prod
ingress:
  enabled: true
  host: www.wakesurfuk.com
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: sha-6b291cf
imagePullSecrets:
  - name: ghcr-login-secret

