environment: prod
ingress:
  enabled: true
  host: www.wakeboard.co.uk
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: sha-a923dff
imagePullSecrets:
  - name: ghcr-login-secret
