environment: test
ingress:
  enabled: true
  host: test.wakeboard.co.uk
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: pr-133-sha-93aed9a
imagePullSecrets:
  - name: ghcr-login-secret
