environment: test
ingress:
  enabled: true
  host: test.wakeboard.co.uk
replicaCount: 1
image:
  repository: ghcr.io/jeremynevill/wakeboarduk
  tag: sha-c6d7785
imagePullSecrets:
  - name: ghcr-login-secret
